twig:
    file_name_pattern: '*.twig'
    globals:
        club_iban: '%club.iban%'
        club_bic: '%club.bic%'
        club_titulaire: '%club.titulaire%'
        social_facebook_url: '%social.facebook_url%'
        social_instagram_url: '%social.instagram_url%'

when@test:
    twig:
        strict_variables: true
