vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        galerie_images:
            uri_prefix: /uploads/galerie
            upload_destination: '%kernel.project_dir%/public/uploads/galerie'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        certificats_medicaux:
            uri_prefix: /private/certificats
            upload_destination: '%kernel.project_dir%/var/uploads/certificats'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        goodies_images:
            uri_prefix: /uploads/goodies
            upload_destination: '%kernel.project_dir%/public/uploads/goodies'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
