# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    env(HELLOASSO_CAMPAIGN_URL): ''
    helloasso.campaign_url: '%env(HELLOASSO_CAMPAIGN_URL)%'
    env(CLUB_IBAN): ''
    env(CLUB_BIC): ''
    env(CLUB_TITULAIRE): ''
    club.iban: '%env(CLUB_IBAN)%'
    club.bic: '%env(CLUB_BIC)%'
    club.titulaire: '%env(CLUB_TITULAIRE)%'
    env(SOCIAL_FACEBOOK_URL): '#'
    env(SOCIAL_INSTAGRAM_URL): '#'
    social.facebook_url: '%env(SOCIAL_FACEBOOK_URL)%'
    social.instagram_url: '%env(SOCIAL_INSTAGRAM_URL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $helloAssoCampaignUrl: '%helloasso.campaign_url%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
